/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppQuizzesIdRouteImport } from './routes/app.quizzes.$id'
import { Route as AppDecksIdRouteImport } from './routes/app.decks.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDecksIdRoute = AppDecksIdRouteImport.update({
  id: '/decks/$id',
  path: '/decks/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/library': typeof AppLibraryRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/library': typeof AppLibraryRoute
  '/app': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/library': typeof AppLibraryRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/library'
    | '/app/'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/library'
    | '/app'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/library'
    | '/app/'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes/$id': {
      id: '/app/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/app/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decks/$id': {
      id: '/app/decks/$id'
      path: '/decks/$id'
      fullPath: '/app/decks/$id'
      preLoaderRoute: typeof AppDecksIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDecksIdRoute: typeof AppDecksIdRoute
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRoute,
  AppIndexRoute: AppIndexRoute,
  AppDecksIdRoute: AppDecksIdRoute,
  AppQuizzesIdRoute: AppQuizzesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
