/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppAssignedRouteImport } from './routes/app.assigned'
import { Route as AppResultsIdRouteImport } from './routes/app.results.$id'
import { Route as AppQuizzesIdRouteImport } from './routes/app.quizzes.$id'
import { Route as AppDecksIdRouteImport } from './routes/app.decks.$id'
import { Route as AppStudyQuizIdRouteImport } from './routes/app.study.quiz.$id'
import { Route as AppStudyDeckIdRouteImport } from './routes/app.study.deck.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignedRoute = AppAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsIdRoute = AppResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIdRoute = AppQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDecksIdRoute = AppDecksIdRouteImport.update({
  id: '/decks/$id',
  path: '/decks/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyQuizIdRoute = AppStudyQuizIdRouteImport.update({
  id: '/study/quiz/$id',
  path: '/study/quiz/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyDeckIdRoute = AppStudyDeckIdRouteImport.update({
  id: '/study/deck/$id',
  path: '/study/deck/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/assigned': typeof AppAssignedRoute
  '/app/classes': typeof AppClassesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/students': typeof AppStudentsRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
  '/app/results/$id': typeof AppResultsIdRoute
  '/app/study/deck/$id': typeof AppStudyDeckIdRoute
  '/app/study/quiz/$id': typeof AppStudyQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/assigned': typeof AppAssignedRoute
  '/app/classes': typeof AppClassesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/students': typeof AppStudentsRoute
  '/app': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
  '/app/results/$id': typeof AppResultsIdRoute
  '/app/study/deck/$id': typeof AppStudyDeckIdRoute
  '/app/study/quiz/$id': typeof AppStudyQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/assigned': typeof AppAssignedRoute
  '/app/classes': typeof AppClassesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/students': typeof AppStudentsRoute
  '/app/': typeof AppIndexRoute
  '/app/decks/$id': typeof AppDecksIdRoute
  '/app/quizzes/$id': typeof AppQuizzesIdRoute
  '/app/results/$id': typeof AppResultsIdRoute
  '/app/study/deck/$id': typeof AppStudyDeckIdRoute
  '/app/study/quiz/$id': typeof AppStudyQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/assigned'
    | '/app/classes'
    | '/app/history'
    | '/app/library'
    | '/app/students'
    | '/app/'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
    | '/app/results/$id'
    | '/app/study/deck/$id'
    | '/app/study/quiz/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/assigned'
    | '/app/classes'
    | '/app/history'
    | '/app/library'
    | '/app/students'
    | '/app'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
    | '/app/results/$id'
    | '/app/study/deck/$id'
    | '/app/study/quiz/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/assigned'
    | '/app/classes'
    | '/app/history'
    | '/app/library'
    | '/app/students'
    | '/app/'
    | '/app/decks/$id'
    | '/app/quizzes/$id'
    | '/app/results/$id'
    | '/app/study/deck/$id'
    | '/app/study/quiz/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assigned': {
      id: '/app/assigned'
      path: '/assigned'
      fullPath: '/app/assigned'
      preLoaderRoute: typeof AppAssignedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results/$id': {
      id: '/app/results/$id'
      path: '/results/$id'
      fullPath: '/app/results/$id'
      preLoaderRoute: typeof AppResultsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quizzes/$id': {
      id: '/app/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/app/quizzes/$id'
      preLoaderRoute: typeof AppQuizzesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decks/$id': {
      id: '/app/decks/$id'
      path: '/decks/$id'
      fullPath: '/app/decks/$id'
      preLoaderRoute: typeof AppDecksIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study/quiz/$id': {
      id: '/app/study/quiz/$id'
      path: '/study/quiz/$id'
      fullPath: '/app/study/quiz/$id'
      preLoaderRoute: typeof AppStudyQuizIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/study/deck/$id': {
      id: '/app/study/deck/$id'
      path: '/study/deck/$id'
      fullPath: '/app/study/deck/$id'
      preLoaderRoute: typeof AppStudyDeckIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssignedRoute: typeof AppAssignedRoute
  AppClassesRoute: typeof AppClassesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDecksIdRoute: typeof AppDecksIdRoute
  AppQuizzesIdRoute: typeof AppQuizzesIdRoute
  AppResultsIdRoute: typeof AppResultsIdRoute
  AppStudyDeckIdRoute: typeof AppStudyDeckIdRoute
  AppStudyQuizIdRoute: typeof AppStudyQuizIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignedRoute: AppAssignedRoute,
  AppClassesRoute: AppClassesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDecksIdRoute: AppDecksIdRoute,
  AppQuizzesIdRoute: AppQuizzesIdRoute,
  AppResultsIdRoute: AppResultsIdRoute,
  AppStudyDeckIdRoute: AppStudyDeckIdRoute,
  AppStudyQuizIdRoute: AppStudyQuizIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
